/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gestion_bancaire2;

//import java.awt.Font;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.text.Element;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import java.util.logging.Level;
import java.util.logging.Logger;





/**
 *
 * @author mickael
 */
public class TableVirement extends javax.swing.JInternalFrame {

    /**
     * Creates new form TableVirement
     */
    Connection conn;
    PreparedStatement st;
    PreparedStatement stt;
    ResultSet resultat;
    public TableVirement() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        voir_list_virement();
        JComboBox();
    }
    
    public void JComboBox()
    {
        
 
        try
        {
           conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banque","root","");
           st = conn.prepareStatement("SELECT numCompte FROM CLIENT");
           resultat = st.executeQuery();
            while (resultat.next()) 
            {
              String numCompte = resultat.getString("numCompte");
              modifNum.addItem(numCompte);
              modifNum2.addItem(numCompte);
            }
        } 
        catch (SQLException e) 
        {
                e.printStackTrace();
        }
}
    
     public void voir_list_virement()
    {
        int Compter;
         try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banque","root","");
            st = conn.prepareStatement("SELECT c1.Nom AS Nom1, c1.Prenom AS Prenom1, c2.Nom AS Nom2, c2.Prenom AS Prenom2, v.numCompte, v.numCompt, v.montant, v.dateTransfert FROM VIREMENT v JOIN CLIENT c1 ON c1.numCompte = v.numCompte JOIN CLIENT c2 ON c2.numCompte = v.numCompt");
            resultat = st.executeQuery();
            
            ResultSetMetaData RSMD = resultat.getMetaData();
            Compter = RSMD.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel) Table_Virement.getModel();
            dft.setRowCount(0);
            
            while (resultat.next())
            {
                Vector v2 = new Vector();
                
                for (int i = 1 ; i<= Compter; i++)
                {
                    String nom = resultat.getString("Nom1");
                    String prenom = resultat.getString("Prenom1");
                    String nomcomplet = nom+" "+prenom;
                    
                    String nom2 = resultat.getString("Nom2");
                    String prenom2 = resultat.getString("Prenom2");
                    String nomcomplet2 = nom2+" "+prenom2;
                    
                    v2.add(resultat.getString("v.numCompte"));
                    v2.add(nomcomplet);
                    v2.add(resultat.getString("v.numCompt"));
                    v2.add(nomcomplet2);
                    v2.add(resultat.getString("v.montant"));
                    v2.add(resultat.getString("v.dateTransfert"));
                }
                dft.addRow(v2);
            }
            
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Virement = new javax.swing.JTable();
        nouveauVirement = new javax.swing.JButton();
        modifMont = new javax.swing.JTextField();
        modifDate = new javax.swing.JTextField();
        modifier = new javax.swing.JButton();
        effacer = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PDF = new javax.swing.JButton();
        modifNum = new javax.swing.JComboBox<>();
        modifNum2 = new javax.swing.JComboBox<>();

        Table_Virement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numCompte", "nom et prenom", "numCompte", "nom et prenom", "montant", "date"
            }
        ));
        Table_Virement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_VirementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Virement);

        nouveauVirement.setText("Virement");
        nouveauVirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauVirementActionPerformed(evt);
            }
        });

        modifier.setBackground(new java.awt.Color(0, 0, 0));
        modifier.setForeground(new java.awt.Color(255, 255, 255));
        modifier.setText("MODIFIER");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        effacer.setBackground(new java.awt.Color(0, 0, 0));
        effacer.setForeground(new java.awt.Color(255, 255, 255));
        effacer.setText("EFFACER");
        effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerActionPerformed(evt);
            }
        });

        Annuler.setBackground(new java.awt.Color(0, 0, 0));
        Annuler.setForeground(new java.awt.Color(255, 255, 255));
        Annuler.setText("ANNULER");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        jLabel1.setText("numCompte");

        jLabel2.setText("numCompte");

        jLabel3.setText("montant");

        jLabel4.setText("dateTransfer");

        PDF.setBackground(new java.awt.Color(0, 0, 0));
        PDF.setForeground(new java.awt.Color(255, 255, 255));
        PDF.setText("GENERER PDF");
        PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFActionPerformed(evt);
            }
        });

        modifNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        modifNum2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nouveauVirement)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(modifier)
                                    .addGap(43, 43, 43)
                                    .addComponent(effacer)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                    .addComponent(Annuler)
                                    .addGap(31, 31, 31)
                                    .addComponent(PDF))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(modifMont, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(modifNum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(modifDate, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(modifNum2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nouveauVirement)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifMont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifier)
                    .addComponent(effacer)
                    .addComponent(Annuler)
                    .addComponent(PDF))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nouveauVirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauVirementActionPerformed
        // TODO add your handling code here:
       AjoutVirement virement = new AjoutVirement(new javax.swing.JFrame(), true);
       virement.setVisible(true);
    }//GEN-LAST:event_nouveauVirementActionPerformed

    private void Table_VirementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_VirementMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_Virement.getModel();
        int selectedIndex = Table_Virement.getSelectedRow();
        String num = (model.getValueAt(selectedIndex,0).toString());
        String num1 = (model.getValueAt(selectedIndex,2).toString());
        Float num2 = Float.parseFloat(model.getValueAt(selectedIndex,4).toString());
        
        modifNum.setSelectedItem(model.getValueAt(selectedIndex,0).toString());
        modifNum2.setSelectedItem(model.getValueAt(selectedIndex,2).toString());
        modifMont.setText(model.getValueAt(selectedIndex,4).toString());
        modifDate.setText(model.getValueAt(selectedIndex,5).toString());
    }//GEN-LAST:event_Table_VirementMouseClicked

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
         try
        {
            DefaultTableModel model = (DefaultTableModel) Table_Virement.getModel();
            int selectedIndex = Table_Virement.getSelectedRow();
            
            String num = (model.getValueAt(selectedIndex,0).toString());
            String num2 = (model.getValueAt(selectedIndex,2).toString());
        
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banque","root","");
            st = conn.prepareStatement("UPDATE VIREMENT SET numCompte=?,numCompt=?,montant=?,dateTransfert=? WHERE numCompte=? AND numCompt=?");
            
            st.setString(1,modifNum.getSelectedItem().toString());
            st.setString(2,modifNum2.getSelectedItem().toString());
            st.setFloat(3,Float.parseFloat(modifMont.getText()));
            st.setString(4,modifDate.getText());
            st.setString(5, num);
            st.setString(6, num2);
            int RT = st.executeUpdate();
            JOptionPane.showMessageDialog(null,"modification valider");
            
            modifNum.setSelectedIndex(0);
            modifNum2.setSelectedIndex(0);
            modifMont.setText("");
            modifDate.setText("");
            
            voir_list_virement();
        }
        catch(SQLException e)
        {
            //System.out.println("erreur");
            e.printStackTrace();
        }   
    }                                        

    private void EffacerActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }//GEN-LAST:event_modifierActionPerformed

    private void effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerActionPerformed
        // TODO add your handling code here:    
         try
        {
            DefaultTableModel model = (DefaultTableModel)Table_Virement.getModel();
            int selectedIndex = Table_Virement.getSelectedRow();
            
            String num = (model.getValueAt(selectedIndex,0).toString());
            String num2 = (model.getValueAt(selectedIndex,2).toString());

        
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banque","root","");
            st = conn.prepareStatement("DELETE FROM VIREMENT WHERE numCompte=? AND numCompt=?");
            st.setString(1, num);
            st.setString(2, num2);
            int reponse = st.executeUpdate();
            JOptionPane.showMessageDialog(null,"suppression effectuer");
            
            modifNum.setSelectedIndex(0);
            modifNum2.setSelectedIndex(0);
            modifMont.setText("");
            modifDate.setText(""); 
             
            
            voir_list_virement();
                  
        }
        catch(SQLException e)
        {
            //System.out.println("erreur");
            e.printStackTrace();
        } 
    }//GEN-LAST:event_effacerActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        modifNum.setSelectedIndex(0);;
        modifNum2.setSelectedIndex(0);
        modifMont.setText("");
        modifDate.setText(""); 
    }//GEN-LAST:event_AnnulerActionPerformed

    private void PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFActionPerformed
        
// TODO add your handling code here:
        
        // Informations du client et du prêt
         // Création de la boîte de dialogue JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        
        // Filtrer uniquement les fichiers avec l'extension .pdf
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Fichiers PDF", "pdf");
        fileChooser.setFileFilter(filter);
        
        // Afficher la boîte de dialogue de sélection de fichier
        int result = fileChooser.showSaveDialog(null);
        
        // Vérifier si l'utilisateur a sélectionné un fichier et a appuyé sur le bouton "Enregistrer"
        if (result == JFileChooser.APPROVE_OPTION) {
            // Obtenir le chemin d'accès sélectionné par l'utilisateur
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            
            try 
            {
                // Utiliser le chemin d'accès pour générer le fichier PDF
                genererPDF(filePath);
            } catch (SQLException ex) {
                Logger.getLogger(TableVirement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
        
    }//GEN-LAST:event_PDFActionPerformed

    public void genererPDF(String filePath) throws SQLException {
        
            // Récupération du montant du débiteur
            st = conn.prepareStatement("SELECT NOM,PRENOM,SOLDET FROM CLIENT WHERE numCompte = ?");
            st.setString(1, modifNum.getSelectedItem().toString());
            resultat = st.executeQuery();
            float soldet1 = 0;
            String nom = "";
            String prenom = "";
            String nomcomplet1 ="";
            while (resultat.next()) 
            {
                 soldet1 = resultat.getFloat("SOLDET");
                 nom = resultat.getString("NOM");
                 prenom = resultat.getString("PRENOM");
                 nomcomplet1 = nom+" "+prenom;
            } 
            
            
            // Récupération du montant du beneficaire
            st = conn.prepareStatement("SELECT NOM,PRENOM,SOLDET FROM CLIENT WHERE numCompte = ?");
            st.setString(1, modifNum2.getSelectedItem().toString());
            resultat = st.executeQuery();
            float soldet2 = 0;
            String nom2 = "";
            String prenom2 = "";
            String nomcomplet2 ="";
            while (resultat.next()) 
            {
                 soldet2 = resultat.getFloat("SOLDET");
                 nom2 = resultat.getString("NOM");
                 prenom2 = resultat.getString("PRENOM");
                 nomcomplet2 = nom2+" "+prenom2;
                 
            }
            
           //System.out.println(soldet1);
           //System.out.println(soldet2);
      
            String nomBanque = "Banque BFV";
            String montante = modifMont.getText();
            String numCompte1 = modifNum.getSelectedItem().toString();
            String numCompte2 = modifNum2.getSelectedItem().toString();
            
            // Chemin de destination du fichier PDF
            String filePathf = filePath ;
            
            // Création du document PDF
            Document document = new Document();
            
            try {
                // Création d'un écrivain PDF
                PdfWriter.getInstance(document, new FileOutputStream(filePathf));
                
                // Ouverture du document
                document.open();
                
                // Ajout du contenu au document
                Font fontTitre = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
                Paragraph banque = new Paragraph(nomBanque, fontTitre);
                banque.setAlignment(Element.ALIGN_CENTER);
                document.add(banque);
                
                Paragraph date = new Paragraph(modifDate.getText(), fontTitre);
                date.setAlignment(Element.ALIGN_CENTER);
                document.add(date);
                
                Paragraph titre = new Paragraph("AVIS DE VIREMENT N°005", fontTitre);
                titre.setAlignment(Element.ALIGN_CENTER);
                document.add(titre);
                
                
                document.add(Chunk.NEWLINE);
                
                Paragraph contenu = new Paragraph();
                contenu.add("\n");
                contenu.add("N° de compte : " + numCompte1 + "(dediteur)\n");
                contenu.add("nom : "+ nomcomplet1 + "\n");
                contenu.add("Solde actuel : " + soldet1 + " Ar\n");
                contenu.add("\n");
                contenu.add("A\n");
                contenu.add("\n");
                contenu.add("N° de compte client : " + numCompte2 + "(beneficiaire)\n");
                contenu.add("nom : "+ nomcomplet2 + "\n");
                contenu.add("Montant : " +montante + " Ar\n");
                contenu.add("solde actuel : " +soldet2 + " Ar\n");
                document.add(contenu);
                
                // Fermeture du document
                document.close();
                
                System.out.println("Fichier PDF généré avec succès !");
                modifNum.setSelectedIndex(0);;
                modifNum2.setSelectedIndex(0);
                modifMont.setText("");
                modifDate.setText(""); 
            } catch (DocumentException | IOException e) {
                e.printStackTrace();
            }
        }         
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton PDF;
    private javax.swing.JTable Table_Virement;
    private javax.swing.JButton effacer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modifDate;
    private javax.swing.JTextField modifMont;
    private javax.swing.JComboBox<String> modifNum;
    private javax.swing.JComboBox<String> modifNum2;
    private javax.swing.JButton modifier;
    private javax.swing.JButton nouveauVirement;
    // End of variables declaration//GEN-END:variables
}
