/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gestion_bancaire2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mickael
 */
public class TableBanque extends javax.swing.JInternalFrame {

    /**
     * Creates new form TableBanque
     */
    Connection conn;
    PreparedStatement st;
    ResultSet resultat;
    
    public TableBanque() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        voir_benefice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void voir_benefice()
    {
        //int Compteur = 0;
        try
        {
        DefaultTableModel banque = (DefaultTableModel) Table_Banque.getModel();
        banque.setRowCount(0);
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banque","root","");
        st = conn.prepareStatement("SELECT montant_preté FROM PRETER");
        resultat = st.executeQuery();
        
        // Calculer le bénéfice accumulé
            double beneficeTotal = 0;
             Vector v2 = new Vector();
            while (resultat.next()) 
            {
                
                int montantPreté = resultat.getInt("montant_preté");
                double beneficePret = montantPreté * 0.1; // Calculer 10% du montant prêté
                beneficeTotal += beneficePret;
                
                
           }
            v2.add(beneficeTotal);
            banque.addRow(v2);
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Banque = new javax.swing.JTable();
        title = new javax.swing.JLabel();

        Table_Banque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "benefice accumuler par la banque en Ariary"
            }
        ));
        jScrollPane1.setViewportView(Table_Banque);

        title.setBackground(new java.awt.Color(255, 0, 102));
        title.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        title.setText("la banque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(title)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Banque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
